# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39aa6044041784adc5e2cd2951424859b376b6f62675980e2726c8df3dbfe5c4f2f65be599758439b1776684749e4ef91febd666d0c217f083e98860839ea7ab

test:
  secret_key_base: 80a515cd9f4d391150a701a5797814ed22f2f9baaf8e96577d2e79e93cb5bc3e46ee07c3fb5ce99c8ce268761880d471aa2ebc743682eb22896e23ce58f63ed6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
