development:
  adapter: postgresql
  database: danebook  
  pool: 5                             
  timeout: 5000

production:
  adapter: postgresql   

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3