# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

s3: &s3
  ACCESS_KEY_ID: <%= ENV["ACCESS_KEY_ID"] %>
  SECRET_ACCESS_KEY: <%= ENV["SECRET_ACCESS_KEY"] %>
  BUCKET: <%= ENV["BUCKET"] %>
  S3_HOST_NAME: <%= ENV["S3_HOST_NAME"] %>
  S3_REGION: <%= ENV["S3_REGION"] %>

development:
  secret_key_base: fdd7e2db9bdbea2450dc734cf3da45cfead76f41d68661f9aa8e975363a9cc1ab9823dafe2fdc60971b776f51c98d737a8fab526950d275cac3d32608cced637
  <<: *s3

test:
  secret_key_base: 5e49c329de33af492da844788003ae43413d73f63d02dc44b593f1f4a769882374e7a20d4ef7036072b9f62f5418073e68a7b474d365fc21febec9000b13b0bd
  <<: *s3
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *s3
