# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a8ab98976c8adefce7471fd7a3d1c240af246cc1dc57ead037ac053faab4f42b5d9f0ee2c3017d9825c535efe6a3e6e87ca18b841207161b336a9e14f5cfee4
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  s3_api_id: <%= ENV["S3_API_ID"] %>
  s3_api_key: <%= ENV["S3_API_KEY"] %>
  s3_region: <%= ENV["S3_REGION"] %>

test:
  secret_key_base: 8ed5c1fef5f8594431a217909d96653bfd594285b6180e7786c16347f7f4671ae5a32a2104643aeaf846a87f832b0f59cbc2595fe2c204f720ae792e1a23b17c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  s3_api_id: <%= ENV["S3_API_ID"] %>
  s3_api_key: <%= ENV["S3_API_KEY"] %>
  s3_region: <%= ENV["S3_REGION"] %>
