# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 004b08f8e7a2a9647713828c849dc038a1b3ac904055d2522111c8def13619a5a4110e2b99e67ab078a909b482e9734e9030b793fa9aeadc1df729fd4f8f8e00
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  s3_bucket_name: <%= ENV['AWS_BUCKET'] %>

test:
  secret_key_base: e0e5c9816405e2a0edc1d9afa022a7f154fd197b4ca386db0108c9fdb3eb6a254a666225fd6f05ed67a2786f44136d89ce8f1cd5675440bdc4ea1fe2d3cf7615

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  s3_bucket_name: <%= ENV['AWS_BUCKET'] %>
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  sendgrid_api_key: <%= ENV['SENDGRID_API_KEY'] %>
