# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfabd013cf788ddbba8f79da6c515e4d91ae3f6ee0a3d0f24c14edd2bcd8fa311087dfe4fd177e923fcbf501bc89dea21795ede0e2413698f8a32bf8278c2078
  aws_id: <%= ENV["AWS_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>

test:
  secret_key_base: 8627d832ad1a4b88ca4df646c911f8653dfe5e00c7a25223198cd316252f9833509442fb614b5bae02a794d32d97a6b018462ed196714c9ec92eeeefbfbdf2f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
