# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efc9d555ce40507ae05049e792121a4e25a33a543b28262b3e868f06706a635647de02b71426c5d5a7527e317ddb2d46b866e43d072749f3c6eb8d42f747c692

test:
  secret_key_base: f2ce2cce7427ecc0d6fc7b33aab0f8dce89123dff3e34ebfd551b612e04ef2095777049956b2b75e13e80e54ebe9070327a0666245a908edf42d43b8b649bee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
