# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f60c8761c32b207d7d8a4573082addbb3747eb643ae3fad01862161ab723cfa0603b324f2ceec398376322f99336b073c3a3284f73d3fadc91bb2e59163e703
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  delay_flag: <%= ENV["DELAY_EMAILS"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  delay_flag: <%= ENV["DELAY_EMAILS"] %>

test:
  secret_key_base: 79ccde9a188d831c801d54f5fd80b6283c9a40b225d0135df75fb304a36c5c375c903c88015c0eaae5c52a168456315a017923851d285c9d4c5bd900ff16095c
