# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9be0675405619669fc0a49e834115ca0a7ce93137120d7521df79a9af2358131e14a7d435e56575156ab0a4408d758739bab0c7fd8f41302f3bfabfe6c07f595
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  delay: <%= ENV['DELAY'] %>

test:
  secret_key_base: b68ec57d3be216e9f932fed5b75d594e24e8a299d2c7370667719006a43152110463be0f9ba3591cafe3be67d4229702a1d9517227f17fa6104bc270f5647fe0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  delay: <%= ENV['DELAY'] %>
