# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
s3: &s3
  ACCESS_KEY_ID: <%= ENV["ACCESS_KEY_ID"] %>
  SECRET_ACCESS_KEY: <%= ENV["SECRET_ACCESS_KEY"] %>
  BUCKET: <%= ENV["BUCKET"] %>
  S3_HOST_NAME: <%= ENV["S3_HOST_NAME"] %>
  S3_REGION: <%= ENV["S3_REGION"] %>


development:
  secret_key_base: c8b1206f1d20d67ea5e95aa581061871c116a14b94602c47b92140002cf55e302a71e74798805cdf0975f0bd7efc87c44fb63b1e1b83605983e35dd8959d08d3
  <<: *s3

test:
  secret_key_base: f14bb056c3e96c185ab880ec413f48560f15005a7292ab6154d7ad18517b3b24dba10c61daa73a61ecfa2d1e5e0404879f6aa5ae586bc6cc2e2320256d9ef932
  <<: *s3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *s3
