# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

aws_s3: &aws_s3
  s3_host_name: <%= ENV['S3_HOST_NAME'] %>
  bucket: <%= ENV['BUCKET'] %>
  access_key_id: <%= ENV['ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['SECRET_ACCESS_KEY'] %>

development:
  <<: *aws_s3
  secret_key_base: 8443f7ea12f778eae378c65ea736a0df987fbc5b44f096d0409e970e95cbe428a1902de08090806eae49598eb7dffafd56bd4b85d67de08a6400d9900035054a

test:
  <<: *aws_s3
  secret_key_base: 4ddfcba4204d228975bd9c949a35c3c8be59149e8a584d51f52d3a9472df97be65bb8dddd52c8557361d59c89337841128049ae3607e66ab735a976d036c00ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *aws_s3
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
